### ISSUE TITLE
Not compatible with angular dart 0.10

### ISSUE THREAD

**Issue by chandu0101** [google/angular_node_bind.dart#4]
import 'package:angular_node_bind/angular_node_bind.dart' show NodeBindModule;
initPolymer().run(() {
    applicationFactory().addModule(new AppModule()).addModule(new NodeBindModule()).run();
  }); 

I am getting following error when using NodeBindModule with angulardart 0.10

Error : 
Internal error: 'package:angular_node_bind/angular_node_bind.dart': malformed type: line 42 pos 2: type 'NgDirective' is not loaded
@NgDirective(selector: r'[_=/[[._]]/]')
 ^

Browser : Dartium

**Comment by justinfagnani** [comment]
Fixed, thanks for the report!
